# Generated by Django 2.1.7 on 2019-02-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('dob', models.DateField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'bus_app',
            },
        ),
    ]
